spring:
  application:
    name: auth-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

keycloak:
  base-url: ${KEYCLOAK_BASE_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: auth
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL}
  resource:
    attributes:
      service.name: ${OTEL_RESOURCE_SERVICE_NAME}
      service.namespace: ${OTEL_RESOURCE_SERVICE_NAMESPACE}
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp


